### ISSUE TITLE
Node 12 deprecation warning on github actions.

### ISSUE THREAD

**Issue by thdelattre** [actionshub/test-kitchen#15]
## :ghost: Brief Description
The last few weeks, we've seen the following message when executing Github Actions
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actionshub/test-kitchen@main
```
## :pancakes: Action version

test-kitchen@main

## Steps To Reproduce

Use "test-kitchen@main" and start an Action

## :police_car: Expected behavior

Action migrated to Node 16

**Comment by damacus** [comment]
Fixed via #16
