### ISSUE TITLE
Add option to leave suite and os empty

### ISSUE THREAD

**Issue by pschaumburg** [actionshub/test-kitchen#2]
## :person_frowning: Problem Statement

Right now, I’m defining my suites and os in my kitchen.yml file and overwriting sections like the driver itself with a different kitchen file. 
But this could always contain differences between every cookbooks.

When I add a new platform, I just want to add this platform into my kitchen.yml file and not additionally to my GH Action yml file.

I know, it will change the behaviour in the view of the action into a single one instead of the matrix way. So it would also be great to have a concurrent option, which could be set. So different suites can be ran at the same time.

## :grey_question: Possible Solution

* Make suite and os optional
* Add concurrent option with numbers as inputs

## :arrow_heading_up: Describe alternatives you've considered

The only way would be not to use this action.

**Comment by damacus** [comment]
Happy to have this feature added if you want to write the code!
