### ISSUE TITLE
OS and Suite are not used

### ISSUE THREAD

**Issue by pschaumburg** [actionshub/test-kitchen#3]
## :ghost: Brief Description

I've created a new repository and added to this empty repo a workflow yml file. This yml file contains 1:1 the first example and nothing more. Now, when I look into the action output, I only see the following command: `/usr/bin/kitchen test -` but nothing with `/usr/bin/kitchen test default-ubuntu-1604`

## :pancakes: Action version

Current master

## :tophat: workflow configuration

See your first example in README

## Steps To Reproduce

See description. 

## :police_car: Expected behavior

It should show the correct command.

**Comment by xorima** [comment]
Readme updated with correct information, thanks for this
